name: Auto-Update

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    name: Auto-Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create local changes
      run: |
        ./update.sh
    - name: Commit files
      run: |
        git config --local user.email "hashhar_dev@outlook.com"
        git config --local user.name "Ashhar Hasan"
        git commit -m "Synced on $(date -I)" -a
    - name: Push changes
      run: |
        git push
